### ISSUE TITLE
way to remain logged in after recreating container?

### ISSUE THREAD

**Issue by kylrth** [duo/matrix-wechat-agent#4]
Hi, great work with this. One annoying thing is that I have to `login` again through matrix every time the agent container restarts. I don't experience this on other bridges (WhatsApp, Signal, etc.), but then again this bridge is much more complicated to implement so I understand. Is there a way to accomplish this maybe by mounting some volume somewhere?

**Comment by duo** [comment]
Currently, there is no solution for this...
Due to the WeChat's security policies, it does not retain login states on other platforms and requires verification through the mobile client.

**Comment by kylrth** [comment]
Bummer. Thanks anyway!
